# Google App Engine configuration
runtime: nodejs20

# Automatic scaling configuration
automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

# Environment variables
env_variables:
  NODE_ENV: production
  SESSION_SECRET: your-secret-key-here

# Health check configuration
health_check:
  enable_health_check: true
  check_interval_sec: 30
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2

# Static file handling
handlers:
- url: /assets
  static_dir: server/public/assets
  secure: always

- url: /.*
  script: auto
  secure: always