# Alternative: Cloud Run configuration
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: medical-handover-app
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cpu-throttling: "false"
    spec:
      containerConcurrency: 1000
      timeoutSeconds: 300
      containers:
      - image: gcr.io/PROJECT_ID/medical-handover-app
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: production
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-url
              key: url
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: session-secret
              key: secret
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.1"
            memory: "128Mi"